### ISSUE TITLE
Allow the tool to be usable with traditional workflows.

### ISSUE THREAD

**Issue by AdrianoRegino** [FrandSX/sxtools2-blender#1]
First would like to congratulate for the incredible job with this addon. 
The tool is very powerful, but it could be also very useful for general vertex coloring tasks.

Far from knowing the complexity of that, but I believe it should basically change the type of vertex color it creates from "Color" to "Byte Color".

![image](https://user-images.githubusercontent.com/127352495/229587234-47ce653c-35c6-4399-925e-a398867472f6.png)

And keep the materials in the object intact.

Those changes should be enough for making this tool the best for "traditional" vertex color management.

**Comment by FrandSX** [comment]
Thank you for the kind words!
Would you expand a little bit on where byte colors are needed?

To the best of my understanding, regardless of the data type, values are still written to vertices in 0-1 range. On top of that, Blender seems to be transitioning to linear vertex color blending that only works with float colors (however, some tools like cut and split still interpolate in srgb which causes unwanted results).

That being said, it shouldn't be a huge problem to add a setting to switch between data types (an older revision of the tool did that once already...) but there may be unexpected blending results after some operations.

**Comment by AdrianoRegino** [comment]
Looks like I´ve misunderstood something, sorry, I'm using Blender 3.4.1 and painted a surface with Blender's standard tools, the standard color layer that got created was Byte Color, after some point I felt I needed better tools, like layers and found SX tools, but could not find a way to use my previews colors with SX, maybe SX could convert any color information to its data type.

Summarizing, considering already existing color was important in my case.

Adding to that, I´ve noticed that as soon we add the first layer, SX tools start doing its magic with the materials, it would be very useful to let the user keep using traditional workflows and keep materials.

Not sure if I was able to make it clearer.

**Comment by FrandSX** [comment]
I just committed version 1.10.0 with a preference setting for creating float or byte colors. Please give it a spin.

**Comment by FrandSX** [comment]
If you have painted vertex colors using Blender's vertex paint tool, it seems to create a Color Attribute layer with the name "Attribute" by default.

Now with the SX Tools 2 version I just committed, you can just create a new layer in the SX Tools UI, and notice it creates a new Color Attribute with the name "Layer 0". You can then just delete that Color Attribute in Blender's UI, and rename any other data layer to "Layer 0" to use it in SX Tools 2 after that.

Note that also any color layer created by SX Tools 2 is directly paintable in Blender's Vertex Paint tool. Just select the layer you want to paint in SX Tools UI, switch to Vertex Paint Tool, and you can brush on the colors.

Please note that the PBR layers (occlusion, transmission, roughness, metallic) are special cases that don't work with the vertex paint tool. The rest should be safe.

**Comment by AdrianoRegino** [comment]
Sounds great, thanks. 
What about keeping the materials?

**Comment by FrandSX** [comment]
The automatic material generation of SX Tools 2 is necessary to work with the multiple layered color attributes in the viewport.

However, if you flatten the SX Tools 2 layer stack, the composited vertex colors in that Color Attribute can easily be used in other Blender materials. SX Tools 2 does not delete any of your own materials, so after you're done with your layers, just assign your regular material back to the object.

If you need to return to SX Tools 2, it will auto-assign its own material.

**Comment by AdrianoRegino** [comment]
Got it, the problem happens when you handle a complex object with 10+ materials, and 40k triangles, reassigning materials is not a simple option.

**Comment by FrandSX** [comment]
Understood, but not easily fixed within the scope of SX Tools 2. The tool does its material assignments before displaying its own UI, so adding a function that stores existing material assignments and restores them after some kind of exit is requested would be somewhat hairy to implement.

If you have any Blender python experience (or happen to know a friendly GPT-4...) a script that stores the current material assignments for the selected meshes and restores them with a button press is fairly straightforward to accomplish.

**Comment by AdrianoRegino** [comment]
Wouldn't it be an option to check on the preferences/options for a bool "Traditional Workflow" or "Not assign material", that would change its behavior since start, changing only the parts that affect the materials? I don't have python experience but could try to do something like what you proposed. Thanks for all this feedback.

**Comment by FrandSX** [comment]
SX Tools 2 actually re-creates its material procedurally for any layer added or deleted, blend mode changed, visibility toggled etc. so toggling it off would really be a complex affair and one I would much prefer to avoid.

I did try GPT-4 just now with the request for a script that saved materials for selected objects, and allowed them to be restored with a button press. It spat out about 80 lines of code that did what was requested without any changes needed. Making custom tools has never been as easy for an artist :)

Thank you for trying out this tool, I hope it'll be useful in your projects.

**Comment by AdrianoRegino** [comment]
With chat GPT 4 and just minor changes:
![image](https://user-images.githubusercontent.com/127352495/229759798-b7594d1b-f70a-47b2-ba62-c0211d77cc8e.png)

**Comment by FrandSX** [comment]
Good stuff :)
